# Generated by Django 5.1.2 on 2025-10-30 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('mensagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
            ],
            options={
                'verbose_name': 'Agendamento de Visita',
                'verbose_name_plural': 'Agendamentos de Visitas',
                'db_table': 'agendamento',
                'ordering': ['-data', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Foto',
                'verbose_name_plural': 'Categorias de Fotos',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_evento', models.CharField(choices=[('casamento', 'Casamento'), ('aniversario', 'Aniversário'), ('corporativo', 'Evento Corporativo'), ('infantil', 'Festas Infantis'), ('outro', 'Outro')], max_length=20)),
                ('num_convidados', models.IntegerField()),
                ('local_evento', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=10)),
                ('pacote_selecionado', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('luxo', 'Luxo')], max_length=20)),
                ('servicos_adicionais', models.TextField(default='[]')),
                ('ideias', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('preco_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Final')),
            ],
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoriafoto')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['-data_upload'],
            },
        ),
    ]
