# Generated by Django 5.1.2 on 2025-11-12 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='aceito_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_aceitos', to=settings.AUTH_USER_MODEL, verbose_name='Aceito por'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='orcamento_associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='app.orcamento', verbose_name='Orçamento Associado'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='recusado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_recusados', to=settings.AUTH_USER_MODEL, verbose_name='Recusado por'),
        ),
    ]
