# Generated by Django 5.1.2 on 2025-11-27 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agendamento_aceito_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato (XX) XXXXX-XXXX ou similar.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='num_convidados',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato (XX) XXXXX-XXXX ou similar.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
